services:
  redis:
    container_name: redis_db
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"] # Enables data persistence

volumes:
  redis_data:
