services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goapp_container
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - mynetwork
    ports:
      - "8080:8080"

networks:
  mynetwork:
    driver: bridge

